services:
  - type: web
    name: wings-ai-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_GEN_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true
    healthCheckPath: /
    plan: starter
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 60
      targetCPUPercent: 60

  - type: mongo
    name: wings-ai-mongodb
    plan: starter
    ipAllowList: [] # Only allow internal connections
